rename fail:
C:\_\Python27\python.exe "C:\__\JetBrains\PyCharm 2016.1.3\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 27202 --file "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw"
pydev debugger: process 7920 is connecting

Connected to pydev debugger (build 145.1504)
fail bash\env.py
fail bash\bash.py
Traceback (most recent call last):
  File "C:\__\JetBrains\PyCharm 2016.1.3\helpers\pydev\pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\__\JetBrains\PyCharm 2016.1.3\helpers\pydev\pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 87, in <module>
    from bash import bash
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\bash.py", line 43, in <module>
    import env
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\env.py", line 219, in <module>
    ur'C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\LALALA.log'
  File "bash\env.py", line 173, in rename
    return _execute(pfo)
  File "bash\env.py", line 177, in _execute
    success = pfo.PerformOperations()
ImportError: caused by ImportError(u"caused by com_error(-2144927744, 'OLE error 0x80270000', None, None)",)