Got running on Phoenix PY2 first pass
ref: using build 3.0.1.dev75841 msw (phoenix)

* Switched wx.gizmos
ThinSplitterWindow for SplitterWindow

* balt.TabDragMixin
Disabled
#~Trace for TabDragMixin~#
Traceback (most recent call last):

File "bash\bash.py", line 447, in main
    import basher
  File
"C:\Program Files\Bethesda Softworks\Oblivion\Mopy\Wrye Bash
Launcher.py", line 63, in load_module
    mod =
imp.load_source(fullname,filename+ext,fp)
  File "bash\basher.py", line
5104, in <module>
    class BashNotebook(wx.Notebook,
balt.TabDragMixin): #
TypeError: Error when calling the metaclass bases

multiple bases have instance lay-out conflict

* Phoenix still needs
work to get statusbar to work like classic at this point,
so will hold
off on that until later, because calculating everything at this
point
might change. NOTE: need to check up with Robin on this with sample app

to ensure everything is hooked in properly.

* NotebookTabs need some
AUI attention and remove TabMixin later when working.

* Phoenix
Deprecations & xwx syntax.

* Trimmed Trailing Space

* small tweak to
balt, fix RuntimeError when closing.